version: 0.2

phases:
  pre_build:
    commands:
      - echo Prepare Laravel Sail Environment
      - docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/var/www/html" -w /var/www/html laravelsail/php82-composer:latest composer install --ignore-platform-reqs
      - echo Copy .env
      - php -r "file_exists('.env') || copy('.env.ci', '.env');"
  build:
    commands:
      - echo Start Laravel Sail
      - ./vendor/bin/sail up -d
      - echo Change permission
      - sudo chmod -R 777 . /var/lib/mysql
      - echo Generate key
      - ./vendor/bin/sail artisan key:generate
      - echo Migrate
      - ./vendor/bin/sail artisan migrate
      - echo Npm build
      - ./vendor/bin/sail npm run build
  post_build:
    commands:
      - echo Test
      - ./vendor/bin/sail test
      - echo Larastan
      - ./vendor/bin/sail artisan larastan --without-tty
